/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author flia montoya guzman
 */
public class VentanaProveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaProveedores
     */
    public VentanaProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNit = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblNomContac = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDirOficina = new javax.swing.JLabel();
        lblCorreoContac = new javax.swing.JLabel();
        lblTelContac = new javax.swing.JLabel();
        lblCelContac = new javax.swing.JLabel();
        TextoNit = new javax.swing.JTextField();
        TextoNombre = new javax.swing.JTextField();
        TextoDireccion = new javax.swing.JTextField();
        TextoCorreo = new javax.swing.JTextField();
        TextoFax = new javax.swing.JTextField();
        TextoTelefono = new javax.swing.JTextField();
        TextoNomContac = new javax.swing.JTextField();
        TextoTelContac = new javax.swing.JTextField();
        TextoCelContac = new javax.swing.JTextField();
        TextoOficina = new javax.swing.JTextField();
        TextoCorreoContac = new javax.swing.JTextField();
        BotonAnterior = new javax.swing.JButton();
        BotonSiguiente = new javax.swing.JButton();
        BotonCrear = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Proveedores");

        lblNit.setText("Nit. de la empresa:*");
        lblNit.setEnabled(false);

        lblNombre.setText("Nombre:*");
        lblNombre.setEnabled(false);

        lblDireccion.setText("Dirección:*");
        lblDireccion.setEnabled(false);

        lblTelefono.setText("Teléfono:*");
        lblTelefono.setEnabled(false);

        lblNomContac.setText("Nombre:*");
        lblNomContac.setEnabled(false);

        lblFax.setText("Fax:*");
        lblFax.setEnabled(false);

        lblCorreo.setText("Correo:*");
        lblCorreo.setEnabled(false);

        jLabel8.setText("Información del contacto:");
        jLabel8.setEnabled(false);

        lblDirOficina.setText("Oficina:*");
        lblDirOficina.setEnabled(false);

        lblCorreoContac.setText("Correo:*");
        lblCorreoContac.setEnabled(false);

        lblTelContac.setText("Teléfono:");
        lblTelContac.setEnabled(false);

        lblCelContac.setText("Celular:*");
        lblCelContac.setEnabled(false);

        TextoNit.setEnabled(false);

        TextoNombre.setEnabled(false);

        TextoDireccion.setEnabled(false);

        TextoCorreo.setEnabled(false);

        TextoFax.setEnabled(false);

        TextoTelefono.setEnabled(false);

        TextoNomContac.setEnabled(false);

        TextoTelContac.setEnabled(false);

        TextoCelContac.setEnabled(false);

        TextoOficina.setEnabled(false);

        TextoCorreoContac.setEnabled(false);

        BotonAnterior.setText("Anterior");

        BotonSiguiente.setText("Siguiente");

        BotonCrear.setText("Crear");
        BotonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearActionPerformed(evt);
            }
        });

        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        BotonGuardar.setText("Guardar");
        BotonGuardar.setEnabled(false);
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonBorrar.setText("Borrar");

        BotonBuscar.setText("Buscar");

        BotonCancelar.setText("Cancelar");
        BotonCancelar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNit)
                                .addComponent(lblDireccion))
                            .addComponent(lblNomContac, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextoDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TextoNit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(lblNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(TextoTelContac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(63, 63, 63)
                                            .addComponent(lblCelContac)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TextoCelContac))
                                        .addComponent(TextoNomContac, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextoCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(TextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                            .addComponent(lblFax)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(TextoFax, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(53, 53, 53)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextoCorreoContac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                .addComponent(TextoOficina, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonSiguiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonCrear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonModificar)))
                        .addGap(53, 53, 53)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblTelContac, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCorreoContac, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(lblDirOficina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNit)
                    .addComponent(TextoNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(TextoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTelefono))
                    .addComponent(lblFax)
                    .addComponent(TextoFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(TextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblNomContac))
                    .addComponent(TextoNomContac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTelContac))
                    .addComponent(TextoTelContac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoCelContac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelContac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDirOficina))
                    .addComponent(TextoOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCorreoContac))
                    .addComponent(TextoCorreoContac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAnterior)
                    .addComponent(BotonSiguiente)
                    .addComponent(BotonCrear)
                    .addComponent(BotonModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGuardar)
                    .addComponent(BotonBorrar)
                    .addComponent(BotonBuscar)
                    .addComponent(BotonCancelar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearActionPerformed
        //Habilitar campos de texto
        TextoNit.setEnabled(true);
        TextoNombre.setEnabled(true);
        TextoDireccion.setEnabled(true);
        TextoTelefono.setEnabled(true);
        TextoFax.setEnabled(true);
        TextoCorreo.setEnabled(true);
        TextoNomContac.setEnabled(true);
        TextoTelContac.setEnabled(true);
        TextoCelContac.setEnabled(true);
        TextoOficina.setEnabled(true);
        TextoCorreoContac.setEnabled(true);
        

        //ponerlos en blanco
        TextoNit.setText("");
        TextoNombre.setText("");
        TextoDireccion.setText("");
        TextoTelefono.setText("");
        TextoFax.setText("");
        TextoCorreo.setText("");
        TextoNomContac.setText("");
        TextoTelContac.setText("");
        TextoCelContac.setText("");
        TextoOficina.setText("");
        TextoCorreoContac.setText("");
       
        
        //Deshabilitar botones
        BotonAnterior.setEnabled(false);
        BotonSiguiente.setEnabled(false);
        BotonBuscar.setEnabled(false);
        BotonCancelar.setEnabled(true);
        BotonGuardar.setEnabled(true);
        BotonModificar.setEnabled(false);
        BotonBorrar.setEnabled(false);
        
        
        
        TextoNit.requestFocusInWindow();
    }//GEN-LAST:event_BotonCrearActionPerformed

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        //Habilitar campos de texto
        TextoNit.setEnabled(true);
        TextoNombre.setEnabled(true);
        TextoDireccion.setEnabled(true);
        TextoTelefono.setEnabled(true);
        TextoFax.setEnabled(true);
        TextoCorreo.setEnabled(true);
        TextoNomContac.setEnabled(true);
        TextoTelContac.setEnabled(true);
        TextoCelContac.setEnabled(true);
        TextoOficina.setEnabled(true);
        TextoCorreoContac.setEnabled(true);
        
        
        //Deshabilitar botones
        BotonAnterior.setEnabled(false);
        BotonSiguiente.setEnabled(false);
        BotonBuscar.setEnabled(false);
        BotonCancelar.setEnabled(true);
        BotonGuardar.setEnabled(true);
        BotonModificar.setEnabled(false);
        BotonBorrar.setEnabled(false);
        
        
        
        TextoNit.requestFocusInWindow();
    }//GEN-LAST:event_BotonModificarActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        TextoNit.setEnabled(false);
        TextoNombre.setEnabled(false);
        TextoDireccion.setEnabled(false);
        TextoTelefono.setEnabled(false);
        TextoFax.setEnabled(false);
        TextoCorreo.setEnabled(false);
        TextoNomContac.setEnabled(false);
        TextoTelContac.setEnabled(false);
        TextoCelContac.setEnabled(false);
        TextoOficina.setEnabled(false);
        TextoCorreoContac.setEnabled(false);
        
        
        //Deshabilitar botones
        BotonAnterior.setEnabled(true);
        BotonSiguiente.setEnabled(true);
        BotonBuscar.setEnabled(true);
        BotonCancelar.setEnabled(false);
        BotonGuardar.setEnabled(false);
        BotonModificar.setEnabled(true);
        BotonBorrar.setEnabled(true);
    }//GEN-LAST:event_BotonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAnterior;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonCrear;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JTextField TextoCelContac;
    private javax.swing.JTextField TextoCorreo;
    private javax.swing.JTextField TextoCorreoContac;
    private javax.swing.JTextField TextoDireccion;
    private javax.swing.JTextField TextoFax;
    private javax.swing.JTextField TextoNit;
    private javax.swing.JTextField TextoNomContac;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoOficina;
    private javax.swing.JTextField TextoTelContac;
    private javax.swing.JTextField TextoTelefono;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCelContac;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreoContac;
    private javax.swing.JLabel lblDirOficina;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNomContac;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelContac;
    private javax.swing.JLabel lblTelefono;
    // End of variables declaration//GEN-END:variables
}
